version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employee_sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_web
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=EmployeeDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"

volumes:
  sql_data:
